version: "2"
services:
  cv:
    build: .
    restart: always
    volumes:
      - "./src:/app/src"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: 'mongo:3.4.1'
    expose:
      - "27017"
    volumes:
      - 'db:/data/db'

volumes:
  db:




